---
# tasks file for virtualbox (Ubuntu specific)

- name: Add APT key for Oracle VirtualBox repository
  apt_key: >
    url={{ virtualbox_key }}
    state=present
  tags: virtualbox

- name: Configure Oracle VirtualBox APT repository
  apt_repository: >
    repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state=present
  tags: virtualbox

- name: Install VirtualBox packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ virtualbox_packages }}"
  tags: virtualbox
